import "./globals.css";
import { REM, Playfair_Display } from "next/font/google";

const root_font = REM({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const head_font = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import ScrollBarTracker from "@/components/shared/ScrollBarTracker";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={root_font.variable}>
        <Navbar />
        <ScrollBarTracker />
        <main>{children}</main>
      </body>
    </html>
  );
}
